Version 1.2

diff --git a/check_snmp_qlogic_port b/check_snmp_qlogic_port
--- a/check_snmp_qlogic_port
+++ b/check_snmp_qlogic_port
@@ -7,9 +7,13 @@
 #
 # - 18.11.2013 Version 1.1
 #	- Port status check bugfix
+# - 13.12.2013 Version 1.2
+#	- Some code optimization
+#	- fixed an problem with the snmp timeout
 #
 # Todo:
 # - get sysdesc from port
+#	Note: hmm, cant find an OID for this. Maybe it doesnt exists?
 # - option for extended errors output
 
 while getopts ":H:C:p:t:w:c:" opt; do
@@ -82,8 +86,14 @@ PORT_TX_SPEED_OID=1.3.6.1.3.94.4.5.1.6.16.0.0.192.221
 PORT_RX_SPEED_OID=1.3.6.1.3.94.4.5.1.7.16.0.0.192.221
 PORT_REAL=$(($PORT+1))
 
-PORT_STATUS=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_STATUS_OID.$PORT_REAL  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
-PORT_ADMIN_STATUS=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_ADMIN_STATUS_OID.$PORT_REAL  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
+PORT_STATUS=`snmpwalk -v2c -Oq -Ov -c $COMMUNITY $HOST $PORT_STATUS_OID.$PORT_REAL`
+if [ "$PORT_STATUS" = '' ]
+then
+	echo "Unknown Error"
+	exit 3
+fi
+
+PORT_ADMIN_STATUS=`snmpwalk -v2c -Oq -Ov -c $COMMUNITY $HOST $PORT_ADMIN_STATUS_OID.$PORT_REAL`
 
 OUTPUT=""
 EXIT_CODE=3
@@ -105,7 +115,7 @@ then
 
 	if [ $PORT_STATUS = 1 ]
 	then
-		PORT_PARTNER_WWPN=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_PARTNER_WWPN_OID.$PORT_REAL.1  | sed -e 's,^.*: ,,' | tr -d ' '`
+		PORT_PARTNER_WWPN=`snmpwalk -v2c -Oq -Ov -c $COMMUNITY $HOST $PORT_PARTNER_WWPN_OID.$PORT_REAL.1  | tr -d ' '`
 		if [[ $PORT_PARTNER_WWPN =~ .*SNMP.* ]]
 		then
 			PORT_PARTNER_WWPN_REAL="0"
@@ -131,8 +141,8 @@ fi
 
 if [ "$TYP" = 'speed' ] && [ $PORT_STATUS = 1 ]
 then
-	PORT_TX_SPEED=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_TX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
-	PORT_RX_SPEED=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_RX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
+	PORT_TX_SPEED=`snmpwalk -Cc -v2c -c $COMMUNITY $HOST $PORT_TX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
+	PORT_RX_SPEED=`snmpwalk -Cc -v2c -c $COMMUNITY $HOST $PORT_RX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
 	PERFDATA="$PERFDATA tx_speed_bytes=$PORT_TX_SPEED"c";;;; rx_speed_bytes=$PORT_RX_SPEED"c";;;;"
 	#echo  "OK - Port $PORT is up, Partner WWPN is $PORT_PARTNER_WWPN_REAL | $PERFDATA"
 	#exit 0
@@ -142,8 +152,8 @@ fi
 
 if [ "$TYP" = 'statistics' ]
 then
-        PORT_TX_SPEED=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_TX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
-        PORT_RX_SPEED=`snmpwalk -v2c -c $COMMUNITY $HOST $PORT_RX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
+        PORT_TX_SPEED=`snmpwalk -Cc -v2c -c $COMMUNITY $HOST $PORT_TX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
+        PORT_RX_SPEED=`snmpwalk -Cc -v2c -c $COMMUNITY $HOST $PORT_RX_SPEED_OID | grep ".0.0.$PORT_REAL ="  | sed -e 's,^.*: ,,' | tr -d ' ' | bc`
         PERFDATA="$PERFDATA tx_speed_bytes=$PORT_TX_SPEED"c";;;; rx_speed_bytes=$PORT_RX_SPEED"c";;;;"
 fi
 
